update python install

diff --git a/packages/python/packaging b/packages/python/packaging
--- a/packages/python/packaging
+++ b/packages/python/packaging
@@ -6,25 +6,29 @@ CPUS=$(grep -c ^processor /proc/cpuinfo)
 
 export HOME=/var/vcap
 
-apt-get -y update
-apt-get -y install --no-install-recommends \
-  libffi-dev \
-  libpython3.11-dev \
+echo "Extracting libffi-3.4.4.tar.gz ..."
+if ! tar xpvf libffi-3.4.4.tar.gz ; then
+  echo "Failed extracting libffi-3.4.4.tar.gz ..."
+  exit 1
+fi
 
-tar xf python/Python-*.tar.xz
-pushd Python*
-  ./configure \
-    --prefix=${BOSH_INSTALL_TARGET} \
-    --with-ensurepip \
-    --enable-shared \
-    --enable-unicode=ucs4
-
-  make -j $CPUS
+echo "Installing libffi..."
+pushd libffi-3.4.4
+  ./configure --prefix="${BOSH_INSTALL_TARGET}"/libffi
+  make
   make install
 popd
 
-for dir in $(ls -d /var/vcap/packages/*/bin); do export PATH=$dir:$PATH; done
-for dir in $(ls -d /var/vcap/packages/*/lib); do export LD_LIBRARY_PATH=$dir:${LD_LIBRARY_PATH:-}; done
+export LDFLAGS=-L${BOSH_INSTALL_TARGET}/libffi/lib
+export CPPFLAGS="-I${BOSH_INSTALL_TARGET}/libffi/include"
+export PKG_CONFIG_PATH=${BOSH_INSTALL_TARGET}/libffi/lib/pkgconfig
+
+tar xf python/Python-*.tar.xz
+pushd Python*
+  ./configure --prefix=$BOSH_INSTALL_TARGET --with-system-ffi --ensure-pip
+  make -j $CPUS
+  make install
+popd
 
 pip3 install --upgrade python/wheel-*-py3-none-any.whl
 pip3 install --upgrade python/pip-*-py3-none-any.whl
